
name: Build Testnet Config

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_config:
    name: Build Testnet Config
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build testnet configs
      run: bash ./scripts/build-genesis.sh

    - name: Build validator names
      run: bash ./scripts/build-validator-names.sh
    
    - name: Build bootnode enr
      run: bash ./scripts/build-boot-enr.sh

    - name: Build nodevars.env
      run: bash ./scripts/build-nodevars.sh

    - name: Build legacy configs
      run: bash ./scripts/build-legacy-config.sh
    
    - name: Check all generated configs
      run: bash ./scripts/check-genesis.sh

    - name: Pack testnet configs
      run: cd dist && tar cfz network-config.tar.gz *

    - name: Upload full config artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./dist/network-config.tar.gz
        name: network-config.tar.gz
    
    - name: Pack legacy testnet configs
      run: cd dist2 && tar cfz testnet-all.tar.gz *

    - name: Upload full config artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./dist2/testnet-all.tar.gz
        name: testnet-all.tar.gz
    
    - name: Upload genesis.json artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./dist/metadata/genesis.json
        name: genesis.json
    
    - name: Upload config.yaml artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./dist/metadata/config.yaml
        name: config.yaml
    - name: Upload genesis.ssz artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./dist/metadata/genesis.ssz
        name: genesis.ssz
    